import { useState } from 'react';
import { HISTORY_THRESHOLD, DEFAULT_HISTORY_SETTINGS, type HistorySettings } from '../historyRecommendations';
import type { useHistoryRecommendations } from '../useHistoryRecommendations';
type Result=ReturnType<typeof useHistoryRecommendations>;
export default function HistoryRecommendationStatus({result,isOwner,onSave}:{result:Result;isOwner:boolean;onSave?:(settings:HistorySettings)=>Promise<void>}) {
 const [saving,setSaving]=useState(false);
 const [message,setMessage]=useState('');
 const settings=result.settings ?? DEFAULT_HISTORY_SETTINGS;
 const valid=Object.values(settings).every(Number.isFinite) && settings.favorite>=0 && settings.favorite<=5 && settings.watched>=0 && settings.watched<=5 && settings.queue>=0 && settings.queue<=5 && settings.presetPercent>=0 && settings.presetPercent<=100 && (settings.presetPercent>0 || settings.favorite+settings.watched+settings.queue>0);
 async function save(){if(!onSave || !valid)return;setSaving(true);setMessage('');try{await onSave(settings);setMessage('Saved for all families.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setSaving(false);}}
 return <section aria-label="Recommendation method" className="mx-5 my-4 rounded-2xl border border-ink-800 bg-ink-900 p-4 text-sm text-ink-300">
   <p className="font-semibold text-ink-100">{result.method==='history' ? 'Based on your family’s movie preferences' : 'Using the shared recommendation preset'}</p>
   <p className="mt-1 text-xs leading-relaxed text-ink-400">{result.profile.ready ? `${result.profile.count} watched films · ${result.profile.queueCount} queued films. Favorites count ${settings.favorite}×, watched ${settings.watched}×, Up Next ${settings.queue}×; each film counts once at its strongest signal. ${result.method === 'history' ? `${100-settings.presetPercent}% personal similarity + ${settings.presetPercent}% shared preset.` : 'Currently previewing the shared preset.'}` : `${result.profile.count} of ${HISTORY_THRESHOLD} distinct watched films with usable metadata. Personal recommendations turn on automatically at ${HISTORY_THRESHOLD}; favorites are optional.`}</p>
   {isOwner && <details className="mt-2"><summary className="min-h-[44px] flex items-center cursor-pointer text-amber-glow">Admin: tune and compare recommendations</summary>
     {onSave && <fieldset disabled={saving} className="my-3 space-y-3">
       <legend className="font-semibold text-ink-100">Recommendation weights</legend>
       <p className="text-xs">Changes preview immediately below. Save applies them to all families. Each film uses its strongest applicable signal; 0 turns a signal off.</p>
       {([['favorite','Favorites'],['watched','Watched'],['queue','Up Next']] as const).map(([key,label])=><label key={key} className="flex items-center justify-between gap-3">{label}<input aria-label={`${label} weight`} type="number" min="0" max="5" step="0.25" value={settings[key]} onChange={e=>{result.setSettings({...settings,[key]:Number(e.target.value)});setMessage('');}} className="w-24 min-h-[44px] rounded-xl bg-ink-800 px-3 text-base" /></label>)}
       <label className="block">Existing preset contribution: {settings.presetPercent}%<input aria-label="Existing preset contribution" type="range" min="0" max="100" step="1" value={settings.presetPercent} onChange={e=>{result.setSettings({...settings,presetPercent:Number(e.target.value)});setMessage('');}} className="block w-full min-h-[44px]" /></label>
       <p className="text-xs">Personal signals: {100-settings.presetPercent}%. Preset: {settings.presetPercent}% from your existing RT, IMDb, age, studio, awards, director, and writer settings. Below {HISTORY_THRESHOLD} watched films, families still use the preset.</p>
       {!valid && <p role="alert">Use weights from 0 to 5 and leave at least one contribution above zero.</p>}
       <div className="flex flex-wrap gap-2"><button type="button" disabled={!valid || saving} onClick={()=>void save()} className="min-h-[44px] rounded-xl bg-amber-glow px-4 font-semibold text-ink-950 disabled:opacity-50">{saving?'Saving…':'Save weights'}</button><button type="button" onClick={()=>{result.setSettings(null);setMessage('');}} className="min-h-[44px] rounded-xl border border-ink-700 px-3">Discard preview</button><button type="button" onClick={()=>result.setSettings({...DEFAULT_HISTORY_SETTINGS,presetPercent:0})} className="min-h-[44px] rounded-xl border border-ink-700 px-3">History + queue only</button></div>
       {message && <p role="status">{message}</p>}
     </fieldset>}
     <label className="block">Preview method<select value={result.requested} onChange={e=>result.setMethod(e.target.value as 'auto'|'history'|'preset')} className="mt-1 min-h-[44px] w-full rounded-xl bg-ink-800 px-3 text-base"><option value="auto">Automatic</option><option value="history" disabled={!result.profile.ready}>Personal blend</option><option value="preset">Shared preset</option></select></label>
     {result.profile.ready && <div className="mt-3 grid grid-cols-2 gap-3">{[['Personal blend',result.history],['Shared preset',result.preset]].map(([label,picks])=><div key={label as string}><h3 className="font-semibold">{label as string}</h3><ol className="mt-2 list-decimal pl-4 space-y-1 text-xs">{(picks as Result['picks']).slice(0,5).map(c=><li key={c.imdbId ?? c.title}>{c.displayTitle ?? c.title}</li>)}</ol></div>)}</div>}
     {result.approximation && <div className="mt-3 text-xs leading-relaxed"><p className="font-semibold">Approximate preset percentages</p><p>{Object.entries(result.approximation.weights).map(([key,value])=>`${key === 'csm' ? 'Age' : key === 'imdb' ? 'IMDb' : key === 'rt' ? 'RT' : key}: ${value}%`).join(' · ')}</p><p className="mt-1">Best local approximation tested on {result.approximation.sampleSize} candidates; average rank distance {result.approximation.meanRankDistance} positions. The personal blend uses movie similarity and cannot be fully represented by these percentages. Preview only; shared weights are unchanged.</p></div>}
   </details>}
 </section>;
}
